mission_params:
  00_global:  #  $/mission_params/00_global
    pinger_frequency: 40
    x_speed_hydro: 0.5
    time_speed_hydro: 20
    safe_depth: 1.0
    elgrandfrero: 1.5 #positif
    elgrandfrera: -1.5 #negatif
    crab:
      x: 1.5
      y: 1.5
      yy: -1.5 #negatif
      timer: 2
  01_gate:  #  $/mission_params/01_gate/
    start_yaw: 100
    speed_yaw: 100 #same as start yaw
    gate_yaw: 8 #ajustement pour faire face a la gate 
    time: 6 #use for time speed
    speed_x: 1
    distance_x: 14 #speedrelativeX
    depth: 0.5 # search_depth
    forward_gate: 2 
  03_paths:   #  $/mission_params/03_paths/
    yaw_fail_path: -45
    max_time_align: 120
    max_time_find: 120
    front_after_path: 1.0
    first_path:
      first_side: left #right
      search_depth: 2
      align_depth: 2
    second_path:
      first_side: left #right
      search_depth: 1.5
      align_depth: 1.5
    no_path:
      yaw_buoy: 0
      x_before_yaw: 2
      x_after_yaw: 2
  04_hit_buoys: #  $/mission_params/04_hit_buoys/
    buoys: jiangshi #jiangshi vetalas draugr answag
    topic_to_listen: /proc_image_processing/simple_jiangshi_result
    filterchain_name: simple_jiangshi 
    filterchain_result: simple_jiangshi_result
    max_alignment: 30
    max_queu_size: 5
    threshold_width: 100
    pixel_to_victory: 850
    initial_bb: 600
    final_bb: 400
    target_width: 0.7
    distance_forward: 1
    ram_dist: 2.0
    time_for_ram: 6
    offset_z: 0
    heading: 0
    search_depth: 2
    end_depth: 1
    step_back: -1.0
    max_time_find: 120
    max_time_align: 120
    hit_to_victory: 8
    simple_hit:
      avoid_forward_x: 3 #distance to path
      speed_x: 1
      yaw: 100 #should be the same as gate
    fail_buoy_x: 2 # distance divide by 2
    suc_buoy_x: 2.5
    avoid:
      depth: 1
      hit_depth: 2.15
      x: 3.5
      y: -3.0
      yaw: -20
      ram: 1.0
  05_bat_wolf: #  $/mission_params/05_bat_wolf/
    bin: bat
    topic_to_listen: /proc_image_processing/simple_bat_wolf_result
    filterchain_name: simple_bat_wolf
    filterchain_result: simple_bat_wolf_result
    deep_result: simple_bat_wolf_result
    search_depth: 1.5
    pixel_to_victory: 350
    hit_to_victory: 10
    max_queu_size: 6
    max_queue_size: 6
    target_height: 0.6
    target_width: 0.3
    param_bb: 250
    time_max_align: 120
    time_max_find: 120
    forward_z: 0.75
    max_z: 4.0
    end_depth: 1.5
    offset:
      x: 0.5
      y: -0.2
      yaw: 0
    handle:
        topic_to_listen: /proc_image_processing/simple_bin_handle_result
        filterchain_name: simple_bin_handle
        hit_to_victory: 10
        search_depth: 2.5
        target_width: 0.1
        target_height: 0.2
        max_queue_size: 6
        pixel_to_victory: 150
        forward_z: 0.75
        param_bb: 350
        max_z: 3.5
  06_slay_vampire: #  $/mission_params/06_slay_vampire/
    max_time_find: 120
    max_time_align: 300
    max_time_aborted: 30
    search_depth: 2.5
    speedx: 0.5
    dl:
      vampire: head
      filterchain_name: simple_vampire
      filterchain_result: simple_vampire_result
      topic_to_listen: /proc_image_processing/simple_vampire_result
      max_alignment: 6
      max_queu_size: 10
      max_time_find: 120
      threshold_width: 100
      pixel_to_victory: 500
      hit_to_victory: 15
      low_hit_to_victory: 10
      target_width: 0.7
      initial_bb: 600
      final_bb: 300
      distance_x: 1
      heading: 0
      search_depth: 2.0
      delay_find: 5
      offset:
        x: 0
        y: 0
        yaw: 0
        z: 0
      end_depth: 0.5
    vc:
      vampire: head
      filterchain_name: simple_vampire_torpille
      filterchain_result: simple_vampire_torpille_result
      topic_to_listen: /proc_image_processing/simple_vampire_torpille_result
      max_alignment: 6
      max_queu_size: 10
      threshold_width: 100
      pixel_to_victory_align: 350
      pixel_to_victory_forward: 350
      hit_to_victory: 10
      target_width: 0.3
      target_height: 0.5
      heading: 0
      search_depth: 2
      initial_bb: 600
      final_bb: 400
      distance_x: 0.75
      offset:
        x: 0.5
        y: 0
        yaw: 0
        z: 0
      end_depth: 1
  07_grab:  #  $/mission_params/07_grab/
    bin: baby #coffins
    topic_to_listen: /proc_image_processing/simple_body_baby_result
    filterchain_name: simple_body_baby
    filterchain_result: simple_body_baby_result
    search_depth: 1.5
    pixel_to_victory: 150
    hit_to_victory: 20
    low_hit_to_victory: 10
    max_queue: 10
    param_bb: 100
    forward_z: 0.5
    target_width: 0.05
    target_height: 0.15
    time_max_align: 120
    max_z: 3.5
    end_depth: 0.5
    offset:
      x: 0.5
      y: 0
      yaw: 0
  99_pinger: #  $/mission_params/99_pinger/
    switch_time: 15
