mission_params:
  00_global:  #  mission_params/00_global
    pinger_frequency: 30
    x_speed_hydro: 1.0
    safe_depth: 1.0
    elgrandfrero: 1.5 #positif
    elgrandfrera: -1.5 #negatif
    crab:
      x: 1.5
      y: 1.5
      yy: -1.5 #negatif
      timer: 2
  01_gate:  #  mission_params/01_gate/
    start_yaw: 240
    speed_yaw: 240 #same as start yaw
    gate_yaw: -90 #ajustement pour faire face a la gate 
    time: 6 #use for time speed
    speed_x: 1.5
    distance_x: 1 #speedrelativeX
    depth: 1 # search_depth
    forward_gate: -2 
  03_paths:   #  mission_params/03_paths/
    face_path: 180
    max_time_align: 120
    max_time_find: 120
    front_after_path: 1.0
    first_path:
      first_side: left #right
      search_depth: 0.5
      align_depth: 0.5
      hit_to_victory: 10
    second_path:
      first_side: left #right
      search_depth: 1.5
      align_depth: 1.5
  04_hit_buoys: #  mission_params/04_hit_buoys/
    buoys: jiangshi #jiangshi vetalas draugr answag
    topic_to_listen: /proc_image_processing/simple_jiangshi_result
    filterchain_name: simple_jiangshi 
    filterchain_result: simple_jiangshi_result
    max_alignment: 30
    max_queu_size: 5
    threshold_width: 200
    pixel_to_victory: 1000
    initial_bb: 600
    final_bb: 400
    target_width: 0.7
    distance_forward: 0.5
    ram_dist: 2.0
    time_for_ram: 10
    offset_z: 0
    heading: 0
    search_depth: 0.7
    end_depth: 0.5
    step_back: -1.0
    max_time_find: 120
    max_time_align: 120
    hit_to_victory: 10
    avoid_forward_x: 3
    avoid:
      depth: 0.5
      hit_depth: 2.5
      x: 3.5
      y: -2.0
      yaw: 190
      ram: 1.0
  05_bat_wolf: #  mission_params/05_bat_wolf/
    bin: bat
    topic_to_listen: /proc_image_processing/simple_bat_wolf_result
    filterchain_name: simple_bat_wolf
    filterchain_result: simple_bat_wolf_result
    deep_result: simple_bat_wolf_result
    search_depth: .5
    pixel_to_victory: 350
    hit_to_victory: 10
    max_queu_size: 6
    max_queue_size: 6
    time_max_align: 120
    time_max_find: 120
    forward_z: 0.5
    max_z: 1.2
    end_depth: 0.5
    offset:
      x: 0.5
      y: -0.2
      yaw: 0
  06_slay_vampire: #  mission_params/06_slay_vampire/
    max_time_find: 120
    max_time_align: 120
    search_depth: 0.5
    speedx: 1.0
    dl:
      vampire: head
      filterchain_name: simple_vampire
      filterchain_result: simple_vampire_result
      topic_to_listen: /proc_image_processing/simple_vampire_result
      max_alignment: 6
      max_queu_size: 10
      max_time_find: 120
      threshold_width: 100
      pixel_to_victory: 350
      hit_to_victory: 10
      target_width: 0.7
      initial_bb: 600
      final_bb: 300
      distance_x: 1
      heading: 0
      search_depth: 2.0
      offset:
        x: 0
        y: 0
        yaw: 0
        z: 0
      end_depth: 0.5
    vc:
      vampire: head
      filterchain_name: simple_vampire_torpille
      filterchain_result: simple_vampire_torpille_result
      topic_to_listen: /proc_image_processing/simple_vampire_torpille_result
      max_alignment: 6
      max_queu_size: 10
      threshold_width: 100
      pixel_to_victory_align: 350
      pixel_to_victory_forward: 350
      hit_to_victory: 10
      target_width: 0.3
      heading: 0
      search_depth: 0.8
      initial_bb: 600
      final_bb: 300
      distance_x: 1
      offset:
        x: 1
        y: -0.3
        yaw: 0
        z: 0
      end_depth: 0.5
  07_grab:  #  mission_params/07_grab/
    bin: baby #coffins
    topic_to_listen: /proc_image_processing/simple_poignee_vampire_result
    filterchain_name: simple_poignee_vampire
    filterchain_result: simple_poignee_vampire_result
    search_depth: 1.0
    pixel_to_victory: 350
    hit_to_victory: 10
    time_max_align: 120
    max_z: 2.6
    end_depth: 0.5
    offset:
      x: 0.5
      y: -0.2
      yaw: 0
