mission_params:
  00_global:
    pinger_frequency: 40
    safe_depth: 1.0
    elgrandfrero: 1.5
    elgrandfrera: -1.5
  01_gate:
    start_yaw: 240
    speed_yaw: 240
    gate_yaw: -90
    time: 6
    speed_x: 1.5
    distance_x: 1
    depth: 1
    forward_gate: -2
  03_paths:
    max_time_align: 120
    front_after_path: 1.0
    first_path:
      first_side: left #right
      search_depth: 1.5
      align_depth: 1.5
      hit_to_victory: 10
    second_path:
      first_side: left #right
      search_depth: 1.5
      align_depth: 1.5
  04_hit_buoys:
    buoys: jiangshi #jiangshi vetalas draugr answag
    topic_to_listen: /proc_image_processing/simple_jiangshi_result
    filterchain_name: simple_jiangshi 
    filterchain_result: simple_jiangshi_result
    max_alignment: 30
    max_queu_size: 3
    threshold_width: 100
    pixel_to_victory: 800
    target_width: 0.7
    distance_forward: 1.0
    ram_dist: 2.0
    time_for_ram: 10
    offset_z: -0.5
    heading: 0
    search_depth: 2.0
    end_depth: 0.5
    step_back: -1.0
    max_time_find: 120
    max_time_align: 120
    hit_to_victory: 4
  05_bat_wolf:
    bin: bat
    topic_to_listen: /proc_image_processing/simple_bat_wolf_result
    filterchain_name: simple_bat_wolf
    filterchain_result: simple_bat_wolf_result
    deep_result: simple_bat_wolf_result
    search_depth: 1.0
    pixel_to_victory: 350
    hit_to_victory: 10
    max_queu_size: 6
    time_max_align: 120
    time_max_find: 120
    forward_z: 0.5
    max_z: 2.6
    end_depth: 0.5
    offset:
      x: 0.5
      y: -0.2
      yaw: 0
  06_slay_vampire:
    max_time_find: 120
    max_time_align: 120
    search_depth: 2.0
    speedx: 1.0
    dl:
      vampire: head
      filterchain_name: simple_vampire
      filterchain_result: simple_vampire_result
      topic_to_listen: /proc_image_processing/simple_vampire_result
      max_alignment: 6
      max_queu_size: 10
      threshold_width: 100
      pixel_to_victory: 350
      hit_to_victory: 10
      target_width: 0.7
      heading: 0
      search_depth: 2.0
      offset:
        x: 0
        y: 0
        yaw: 0
        z: 0
      end_depth: 0.5
    vc:
      vampire: head
      filterchain_name: simple_vampire_torpille
      filterchain_result: simple_vampire_torpille_result
      topic_to_listen: /proc_image_processing/simple_vampire_result
      max_alignment: 6
      max_queu_size: 10
      threshold_width: 100
      pixel_to_victory: 350
      hit_to_victory: 10
      target_width: 0.7
      heading: 0
      search_depth: 2.0
      offset:
        x: 0
        y: 0
        yaw: 0
        z: 0
      end_depth: 0.5
  07_grab:
    bin: baby #coffins
    topic_to_listen: /proc_image_processing/simple_poignee_vampire_result
    filterchain_name: simple_poignee_vampire
    filterchain_result: simple_poignee_vampire_result
    search_depth: 1.0
    pixel_to_victory: 350
    hit_to_victory: 10
    time_max_align: 120
    max_z: 2.6
    end_depth: 0.5
    offset:
      x: 0.5
      y: -0.2
      yaw: 0
  90_random_pinger:
    presearching_depth: 0.5
    searching_depth: 1.0
