mission_params:
  00_global:
    color: black #red
    pinger_frequency: 35
  01_find_casino:
    #rotation_scale: 1
    depth: 1.0
    angle1_deg: 90
    angle2_deg: 90
    final_global_angle: 175
  02_enter_casino:
    black_side: left #right
  03_paths:
    first_path:
      first_side: left #right
      search_depth: 1.5
      align_depth: 1.5
    second_path:
      first_side: left #right
      search_depth: 1.5
      align_depth: 1.5
  04_shoot_craps:
    sum_11:
      first_dice:
        dice: 5 # 2, 4 or 6
        approx_depth: 2.0
        ram_distance: 1.5
        back_distance: -1.5  
        max_time: 120 
        filterchain_name: 'simple_dice5'
      second_dice:
        dice: 6 # 2, 4 or 6
        approx_depth: 1.5
        ram_distance: 1.5
        back_distance: -1.5  
        max_time: 120 
        filterchain_name: 'simple_dice6'
      complementary_1:
        dice: 1 # 2, 4 or 6
        approx_depth: 1.5
        ram_distance: 1.5
        back_distance: -1.5  
        max_time: 120 
        filterchain_name: 'simple_dice1'
      complementary_2:
        dice: 2 # 2, 4 or 6
        approx_depth: 1.5
        ram_distance: 1.5
        back_distance: -1.5  
        max_time: 120 
        filterchain_name: 'simple_dice2'
    sum_07:
      first_dice:
        dice: 6 # 2, 4 or 6
        approx_depth: 2.0
        ram_distance: 1.5
        back_distance: -1.5  
        max_time: 120 
        filterchain_name: 'simple_dice6'
      second_dice:
        dice: 1 # 2, 4 or 6
        approx_depth: 1.5
        ram_distance: 1.5
        back_distance: -1.5  
        max_time: 120 
        filterchain_name: 'simple_dice1'
      complementary_1:
        dice: 2 # 2, 4 or 6
        approx_depth: 1.5
        ram_distance: 1.5
        back_distance: -1.5  
        max_time: 120 
        filterchain_name: 'simple_dice2'
    last_dices:
      first_dice:
        dice: 1 # 2, 4 or 6
        approx_depth: 2.0
        ram_distance: 1.5
        back_distance: -1.5  
        max_time: 120 
        filterchain_name: 'simple_dice1'
      second_dice:
        dice: 2 # 2, 4 or 6
        approx_depth: 1.5
        ram_distance: 1.5
        back_distance: -1.5  
        max_time: 120 
        filterchain_name: 'simple_dice2'
  05_buy_gold_chip:
    approx_depth: 2.0
  06_play_slots:
    approx_depth: 1.5
  07_play_roulette:
    searching_depth: 1.5
    final_depth: 3.1
  08_cash_in:
    searching_depth: 2.0
  90_random_pinger:
    searching_depth: 2.0